### ISSUE TITLE
User cannot un-favorite & un-add-to-cook recipes

### ISSUE THREAD

**Issue by brycemara** [brycemara/whats-cookin#31]
As a user

Given I have favorited and added to cook recipes

When I search other recipes and decide to un-favorite or un-addToCook 

Then the recipe icons don't un-highlight

**Comment by Shawntru** [comment]
Replication:

Search for 'sesame'
On search results, 'Heart' or 'Cook Later' by clicking the icon on the sesame cookie recipe
Click Home icon
Search for 'sesame'
'Heart' and 'Cook Later' icons cannot be changed back to unlicked version, although they are removed from respective lists.
